# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_lastname', models.CharField(max_length=50)),
                ('patient_firstname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'patient_info',
            },
        ),
    ]
